"""Added payment tables

Revision ID: 01616b8ebf04
Revises: 38eb3318fd81
Create Date: 2023-05-05 21:45:06.899128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01616b8ebf04'
down_revision = '38eb3318fd81'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_addons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('payment_name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_addons_name'), 'payment_addons', ['name'], unique=False)
    op.create_table('payment_base',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('payment_name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_base_name'), 'payment_base', ['name'], unique=False)
    op.create_table('payment_global_coefficient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('payment_name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('salary', sa.Boolean(), nullable=True),
    sa.Column('pension', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_global_coefficient_name'), 'payment_global_coefficient', ['name'], unique=False)
    op.create_table('payment_increase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('payment_name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_increase_name'), 'payment_increase', ['name'], unique=False)
    op.create_table('payment_pension_duty_coefficient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_pension_duty_coefficient_name'), 'payment_pension_duty_coefficient', ['name'], unique=False)
    op.create_table('payment_single_addon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('payment_name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('default_state', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_single_addon_name'), 'payment_single_addon', ['name'], unique=False)
    op.create_table('payment_addons_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('addon_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['addon_id'], ['payment_addons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_addons_values_name'), 'payment_addons_values', ['name'], unique=False)
    op.create_table('payment_base_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('base_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['base_id'], ['payment_base.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_base_values_name'), 'payment_base_values', ['name'], unique=False)
    op.create_table('payment_match_base_addon',
    sa.Column('base_id', sa.Integer(), nullable=False),
    sa.Column('addon_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['addon_id'], ['payment_addons.id'], ),
    sa.ForeignKeyConstraint(['base_id'], ['payment_base.id'], ),
    sa.PrimaryKeyConstraint('base_id', 'addon_id'),
    sa.UniqueConstraint('base_id', 'addon_id')
    )
    op.create_table('payment_match_base_increase',
    sa.Column('base_id', sa.Integer(), nullable=False),
    sa.Column('payment_increase_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['base_id'], ['payment_base.id'], ),
    sa.ForeignKeyConstraint(['payment_increase_id'], ['payment_increase.id'], ),
    sa.PrimaryKeyConstraint('base_id', 'payment_increase_id'),
    sa.UniqueConstraint('base_id', 'payment_increase_id')
    )
    op.create_table('payment_match_base_single',
    sa.Column('base_id', sa.Integer(), nullable=False),
    sa.Column('single_addon_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['base_id'], ['payment_base.id'], ),
    sa.ForeignKeyConstraint(['single_addon_id'], ['payment_single_addon.id'], ),
    sa.PrimaryKeyConstraint('base_id', 'single_addon_id'),
    sa.UniqueConstraint('base_id', 'single_addon_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_match_base_single')
    op.drop_table('payment_match_base_increase')
    op.drop_table('payment_match_base_addon')
    op.drop_index(op.f('ix_payment_base_values_name'), table_name='payment_base_values')
    op.drop_table('payment_base_values')
    op.drop_index(op.f('ix_payment_addons_values_name'), table_name='payment_addons_values')
    op.drop_table('payment_addons_values')
    op.drop_index(op.f('ix_payment_single_addon_name'), table_name='payment_single_addon')
    op.drop_table('payment_single_addon')
    op.drop_index(op.f('ix_payment_pension_duty_coefficient_name'), table_name='payment_pension_duty_coefficient')
    op.drop_table('payment_pension_duty_coefficient')
    op.drop_index(op.f('ix_payment_increase_name'), table_name='payment_increase')
    op.drop_table('payment_increase')
    op.drop_index(op.f('ix_payment_global_coefficient_name'), table_name='payment_global_coefficient')
    op.drop_table('payment_global_coefficient')
    op.drop_index(op.f('ix_payment_base_name'), table_name='payment_base')
    op.drop_table('payment_base')
    op.drop_index(op.f('ix_payment_addons_name'), table_name='payment_addons')
    op.drop_table('payment_addons')
    # ### end Alembic commands ###
