"""Added db tables

Revision ID: 2d9796a35731
Revises: 
Create Date: 2023-12-15 12:54:28.390357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8419aa221f17'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_addons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('payment_name', sa.String(length=128), nullable=False),
    sa.Column('salary', sa.Boolean(), nullable=False),
    sa.Column('pension', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_addons_slug'), 'payment_addons', ['slug'], unique=True)
    op.create_table('payment_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('payment_name', sa.String(length=128), nullable=False),
    sa.Column('salary', sa.Boolean(), nullable=False),
    sa.Column('pension', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_rates_slug'), 'payment_rates', ['slug'], unique=True)
    op.create_table('production_calendar_holidays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('production_calendar_working_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('users_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('payment_addons_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('addon_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['addon_id'], ['payment_addons.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['payment_documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_global_coefficient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('payment_name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('salary', sa.Boolean(), nullable=False),
    sa.Column('pension', sa.Boolean(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['payment_documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_global_coefficient_slug'), 'payment_global_coefficient', ['slug'], unique=True)
    op.create_table('payment_increase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['payment_documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_match_rate_addon',
    sa.Column('rate_id', sa.Integer(), nullable=False),
    sa.Column('addon_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['addon_id'], ['payment_addons.id'], ),
    sa.ForeignKeyConstraint(['rate_id'], ['payment_rates.id'], ),
    sa.PrimaryKeyConstraint('rate_id', 'addon_id'),
    sa.UniqueConstraint('rate_id', 'addon_id')
    )
    op.create_table('payment_pension_duty_coefficient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['payment_documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_rates_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('rate_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['payment_documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rate_id'], ['payment_rates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_single_addons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('payment_name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('salary', sa.Boolean(), nullable=False),
    sa.Column('pension', sa.Boolean(), nullable=False),
    sa.Column('default_state', sa.Boolean(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['payment_documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_single_addons_slug'), 'payment_single_addons', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['users_roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('payment_match_rate_increase',
    sa.Column('rate_id', sa.Integer(), nullable=False),
    sa.Column('increase_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['increase_id'], ['payment_increase.id'], ),
    sa.ForeignKeyConstraint(['rate_id'], ['payment_rates.id'], ),
    sa.PrimaryKeyConstraint('rate_id', 'increase_id'),
    sa.UniqueConstraint('rate_id', 'increase_id')
    )
    op.create_table('payment_match_rate_single',
    sa.Column('rate_id', sa.Integer(), nullable=False),
    sa.Column('single_addon_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rate_id'], ['payment_rates.id'], ),
    sa.ForeignKeyConstraint(['single_addon_id'], ['payment_single_addons.id'], ),
    sa.PrimaryKeyConstraint('rate_id', 'single_addon_id'),
    sa.UniqueConstraint('rate_id', 'single_addon_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_match_rate_single')
    op.drop_table('payment_match_rate_increase')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_payment_single_addons_slug'), table_name='payment_single_addons')
    op.drop_table('payment_single_addons')
    op.drop_table('payment_rates_values')
    op.drop_table('payment_pension_duty_coefficient')
    op.drop_table('payment_match_rate_addon')
    op.drop_table('payment_increase')
    op.drop_index(op.f('ix_payment_global_coefficient_slug'), table_name='payment_global_coefficient')
    op.drop_table('payment_global_coefficient')
    op.drop_table('payment_addons_values')
    op.drop_table('users_roles')
    op.drop_table('production_calendar_working_days')
    op.drop_table('production_calendar_holidays')
    op.drop_index(op.f('ix_payment_rates_slug'), table_name='payment_rates')
    op.drop_table('payment_rates')
    op.drop_table('payment_documents')
    op.drop_index(op.f('ix_payment_addons_slug'), table_name='payment_addons')
    op.drop_table('payment_addons')
    # ### end Alembic commands ###
