"""Added staff_allowed_faculty table

Revision ID: 55406f6f1309
Revises: 9ef4fce3da4e
Create Date: 2024-02-09 15:33:31.531961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55406f6f1309'
down_revision = '9ef4fce3da4e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_allowed_faculty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apeks_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('apeks_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staff_allowed_faculty')
    # ### end Alembic commands ###
