"""Edit staff_various_busy_types table

Revision ID: 72a584f9215c
Revises: 992e3782a12e
Create Date: 2024-04-04 12:08:31.620013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72a584f9215c'
down_revision = '992e3782a12e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff_various_busy_types', sa.Column('match', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff_various_busy_types', 'match')
    # ### end Alembic commands ###
