"""Added payment tables

Revision ID: 8419aa221f17
Revises: 38eb3318fd81
Create Date: 2023-05-12 00:52:58.219985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8419aa221f17'
down_revision = '38eb3318fd81'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_addons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('payment_name', sa.String(length=128), nullable=True),
    sa.Column('salary', sa.Boolean(), nullable=True),
    sa.Column('pension', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_addons_slug'), 'payment_addons', ['slug'], unique=True)
    op.create_table('payment_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('payment_name', sa.String(length=128), nullable=True),
    sa.Column('salary', sa.Boolean(), nullable=True),
    sa.Column('pension', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_rate_slug'), 'payment_rate', ['slug'], unique=True)
    op.create_table('payment_addons_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('addon_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['addon_id'], ['payment_addons.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['payment_documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_global_coefficient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('payment_name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('salary', sa.Boolean(), nullable=True),
    sa.Column('pension', sa.Boolean(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['payment_documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_global_coefficient_slug'), 'payment_global_coefficient', ['slug'], unique=True)
    op.create_table('payment_increase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['payment_documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_match_rate_addon',
    sa.Column('rate_id', sa.Integer(), nullable=False),
    sa.Column('addon_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['addon_id'], ['payment_addons.id'], ),
    sa.ForeignKeyConstraint(['rate_id'], ['payment_rate.id'], ),
    sa.PrimaryKeyConstraint('rate_id', 'addon_id'),
    sa.UniqueConstraint('rate_id', 'addon_id')
    )
    op.create_table('payment_pension_duty_coefficient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['payment_documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_rate_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rate_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['payment_documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rate_id'], ['payment_rate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_single_addon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('payment_name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('salary', sa.Boolean(), nullable=True),
    sa.Column('pension', sa.Boolean(), nullable=True),
    sa.Column('default_state', sa.Boolean(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['payment_documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_single_addon_slug'), 'payment_single_addon', ['slug'], unique=True)
    op.create_table('payment_match_rate_increase',
    sa.Column('rate_id', sa.Integer(), nullable=False),
    sa.Column('payment_increase_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['payment_increase_id'], ['payment_increase.id'], ),
    sa.ForeignKeyConstraint(['rate_id'], ['payment_rate.id'], ),
    sa.PrimaryKeyConstraint('rate_id', 'payment_increase_id'),
    sa.UniqueConstraint('rate_id', 'payment_increase_id')
    )
    op.create_table('payment_match_rate_single',
    sa.Column('rate_id', sa.Integer(), nullable=False),
    sa.Column('single_addon_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rate_id'], ['payment_rate.id'], ),
    sa.ForeignKeyConstraint(['single_addon_id'], ['payment_single_addon.id'], ),
    sa.PrimaryKeyConstraint('rate_id', 'single_addon_id'),
    sa.UniqueConstraint('rate_id', 'single_addon_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_match_rate_single')
    op.drop_table('payment_match_rate_increase')
    op.drop_index(op.f('ix_payment_single_addon_slug'), table_name='payment_single_addon')
    op.drop_table('payment_single_addon')
    op.drop_table('payment_rate_values')
    op.drop_table('payment_pension_duty_coefficient')
    op.drop_table('payment_match_rate_addon')
    op.drop_table('payment_increase')
    op.drop_index(op.f('ix_payment_global_coefficient_slug'), table_name='payment_global_coefficient')
    op.drop_table('payment_global_coefficient')
    op.drop_table('payment_addons_values')
    op.drop_index(op.f('ix_payment_rate_slug'), table_name='payment_rate')
    op.drop_table('payment_rate')
    op.drop_table('payment_documents')
    op.drop_index(op.f('ix_payment_addons_slug'), table_name='payment_addons')
    op.drop_table('payment_addons')
    # ### end Alembic commands ###
