"""Added user permissions tables

Revision ID: 9ef4fce3da4e
Revises: ad5b891a7b14
Create Date: 2024-02-03 17:05:23.923110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ef4fce3da4e'
down_revision = 'ad5b891a7b14'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users_roles_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['users_permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['users_roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id'),
    sa.UniqueConstraint('role_id', 'permission_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_roles_permissions')
    op.drop_table('users_permissions')
    # ### end Alembic commands ###
