"""Added branch_id field to staff_allowed_faculty

Revision ID: fa9d85924a7b
Revises: 72a584f9215c
Create Date: 2024-12-05 22:27:54.039228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa9d85924a7b'
down_revision = '72a584f9215c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff_allowed_faculty', sa.Column('branch_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff_allowed_faculty', 'branch_id')
    # ### end Alembic commands ###
